"""add backup failure restore tables

Revision ID: 3978e16da6cb
Revises: 4f86840a11e5
Create Date: 2026-08-05 11:19:32.129766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3978e16da6cb'
down_revision: Union[str, Sequence[str], None] = '4f86840a11e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_id'), 'failures', ['id'], unique=False)
    op.create_table('restores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recovery_time', sa.DateTime(), nullable=False),
    sa.Column('rto_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restores_id'), 'restores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restores_id'), table_name='restores')
    op.drop_table('restores')
    op.drop_index(op.f('ix_failures_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_table('backups')
    # ### end Alembic commands ###
