"""add s3 object key to backups

Revision ID: 718211d80ecf
Revises: 3978e16da6cb
Create Date: 2026-08-10 17:33:29.045588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718211d80ecf'
down_revision: Union[str, Sequence[str], None] = '3978e16da6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('s3_object_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 's3_object_key')
    # ### end Alembic commands ###
